name: Robot - extract ontology terms

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install ROBOT
        run: |
          wget --quiet https://github.com/ontodev/robot/releases/download/v1.8.1/robot.jar
          curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > robot 
          chmod +x robot
          ls -l .
          sudo mv ./robot /usr/local/bin
          sudo mv ./robot.jar /usr/local/bin
          robot --help

      - name: download sourceontologies
          pwd
          cd .github/workflows/robot_extract
          bash download_src_ontologies.sh\
          ls .

      - name: extract terms
        run: |
          cd .github/workflows/robot_extract
          bash extract_terms.sh
          ls . 
          head merged.ttl 

# shall the scripts and be inside the .github/workflows dir 

      # - name: convert owl to ttl
      #   run: |
      #     robot convert --input nmrCV.owl --output nmrCV.ttl
      
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: nmrCV_ttl
      #     path: nmrCV.ttl
