name: Robot - extract ontology terms

on:
  workflow_dispatch:

jobs:
  extract-terms-from-ontologies:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install ROBOT
        run: |
          wget --quiet https://github.com/ontodev/robot/releases/download/v1.8.1/robot.jar
          curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > robot 
          chmod +x robot
          ls -l .
          sudo mv ./robot /usr/local/bin
          sudo mv ./robot.jar /usr/local/bin
          robot --help

      # todo: create ontotologies_files.txt from ontologies.txt

      - uses: actions/cache@v2
        id: cache
        with:
          path: .github/workflows/robot_extract
          key: ${{ runner.os }}-ontologies-${{ hashFiles('**/ontotologies_files.txt') }}
          restore-keys: |
            ${{ runner.os }}-ontologies-
       # NOTE: in order to cache the ontology files their filenames need to be saved in ontotologies_files.txt  
        
      - name: download source ontologies
        run: |
          cd .github/workflows/robot_extract
          cat ontologies.txt
          # ls .
          echo "---- download ontology owl files ----"
          while read -r prefix uri method inter; do echo $prefix $uri $method $inter; done < "ontologies.txt"
          # wget --quiet $uri -c; \
          # done < "ontologies.txt"
          # ls .
# "prefix:" $prefix "uri:" $uri $prefix.owl  "method:" $method  "inter:"


      # # values for vars $prefix $uri $method $inter are set in ontologies.txt
      # - name: extract terms from ontologies into single .ttl files
      #   run: |
      #     cd .github/workflows/robot_extract
      #     echo "---- extract terms from ontology owl files ----"          
      #     while IFS=" " read -r prefix uri method inter; \
      #     do if test -f "terms_$prefix.txt"; \
      #     then robot extract --method $method --input $prefix.owl --term-file terms_$prefix.txt --intermediates $inter \
      #     --annotate-with-source true --output extracted_$prefix.owl; \
      #     fi; \
      #     done < "ontologies.txt"
      #     echo "---- convert extracted terms files to ttl ----"
      #     while IFS=" " read -r prefix uri method inter; \
      #     do if test -f "terms_$prefix.txt"; \
      #     then robot convert --input extracted_$prefix.owl --output extracted_$prefix.ttl; \
      #     fi; \
      #     done < "ontologies.txt"

      # - name: merge extracted terms into  merged.ttl 
      #   run: |
      #     cd .github/workflows/robot_extract     
      #     robot merge --inputs "extracted_*.owl" --output merged.owl
      #     robot convert --input merged.owl --output merged.ttl 

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: extracted_terms
      #     path: .github/workflows/robot_extract/*.ttl
