name: test cache

on:
  workflow_dispatch:

jobs:
  extract-terms-from-ontologies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    # # issue: cache is caching ontologies.txt - shouldn't!! Hence this step and next (download source ontologies) are disabled
    # # todo: create ontotologies_files.txt from ontologies.txt
    #   - uses: actions/cache@v2
    #     id: cache
    #     with:
    #       path: .github/workflows/robot_extract
    #       key: ${{ runner.os }}-ontologies-${{ hashFiles('**/ontotologies_files.txt') }}
    #       restore-keys: |
    #         ${{ runner.os }}-ontologies-
    #    # NOTE: in order to cache the ontology files their filenames need to be saved in ontotologies_files.txt  
  download sourcename: test cache

on:
  workflow_dispatch:

jobs:
  extract-terms-from-ontologies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    # # issue: cache is caching ontologies.txt - shouldn't!! Hence this step and next (download source ontologies) are disabled
    # # todo: create ontotologies_files.txt from ontologies.txt
    #   - uses: actions/cache@v2
    #     id: cache
    #     with:
    #       path: .github/workflows/robot_extract
    #       key: ${{ runner.os }}-ontologies-${{ hashFiles('**/ontotologies_files.txt') }}
    #       restore-keys: |
    #         ${{ runner.os }}-ontologies-
    #    # NOTE: in order to cache the ontology files their filenames need to be saved in ontotologies_files.txt  
  download sourcename: test cache

on:
  workflow_dispatch:

jobs:
  extract-terms-from-ontologies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: pwd
        run: |
          pwd
          ls

      - name: mkdir ontologies
          run: |
            cd .github/workflows/test_cache
            mkdir ontologies/
            echo "---- ontologies/ dir ----"          
            ls ./ontologies
    
      - name: Cache ontologies
        id: cache-ontology-files
        uses: actions/cache@v2
        with:
          path: ontologies
          key: ontologies-${{ hashFiles('ontologies.txt') }} # has ontologies.txt # if changes occurs cache is rebuilt

      - name: download source ontologies
        if: steps.cache.outputs.cache-hit != 'true'      
        run: |
          cd .github/workflows/test_cache
          echo "---- ls ontologies/ dir ----"          
          ls ./ontologies
          echo "---- cat ontologies.txt content ----"          
          cat ontologies.txt
          echo "---- download ontology owl files ----"
          while read -r prefix uri method inter; do echo $uri; wget --quiet $uri -c -P ontologies/; done < "ontologies.txt"
          echo "---- ls ontologies/ dir ----"          

      - name: list ontologies
        run: |
          ls ./ontologies

      - name: mkdir ontologies
        run: |
          cd .github/workflows/test_cache
          mkdir ontologies/
          echo "---- ontologies/ dir ----"          
          ls ./ontologies
    
      - name: Cache ontologies
        id: cache-ontology-files
        uses: actions/cache@v2
        with:
          path: ontologies
          key: ontologies-${{ hashFiles('ontologies.txt') }} # has ontologies.txt # if changes occurs cache is rebuilt

      - name: download source ontologies
        if: steps.cache.outputs.cache-hit != 'true'      
        run: |
          cd .github/workflows/test_cache
          echo "---- ls ontologies/ dir ----"          
          ls ./ontologies
          echo "---- cat ontologies.txt content ----"          
          cat ontologies.txt
          echo "---- download ontology owl files ----"
          while read -r prefix uri method inter; do echo $uri; wget --quiet $uri -c -P ontologies/; done < "ontologies.txt"
          echo "---- ls ontologies/ dir ----"          

      - name: list ontologies
        run: |
          ls ./ontologies

      - name: mkdir ontologies
        run: |
          cd .github/workflows/test_cache
          mkdir ontologies/
          echo "---- ontologies/ dir ----"          
          ls ./ontologies
    
      - name: Cache ontologies
        id: cache-ontology-files
        uses: actions/cache@v2
        with:
          path: ontologies
          key: ontologies-${{ hashFiles('ontologies.txt') }} # has ontologies.txt # if changes occurs cache is rebuilt

      - name: download source ontologies
        if: steps.cache.outputs.cache-hit != 'true'      
        run: |
          cd .github/workflows/test_cache
          echo "---- ls ontologies/ dir ----"          
          ls ./ontologies
          echo "---- cat ontologies.txt content ----"          
          cat ontologies.txt
          echo "---- download ontology owl files ----"
          while read -r prefix uri method inter; do echo $uri; wget --quiet $uri -c -P ontologies/; done < "ontologies.txt"
          echo "---- ls ontologies/ dir ----"          

      - name: list ontologies
        run: |
          ls ./ontologies
